### ISSUE TITLE
Inconsistent behavior for form submit event

### ISSUE THREAD

**Issue by simonihmig** [rwjblue/ember-native-dom-event-dispatcher#12]
Given this test case, where the **submit button component would return false from its `click()` event handler**:

```
test('Clicking a submit button submits the form', async function(assert) {
  let submit = this.spy();
  this.on('submit', submit);
  this.render(hbs`{{#bs-form onSubmit=(action "submit")}}{{#bs-button buttonType="submit"}}Submit{{/bs-button}}{{/bs-form}}`);

  await click('button');
  assert.ok(submit.called, 'onSubmit action has been called');
});
```

This test was passing with the native DOM event dispatcher, while the default one would fail!
Meaning that in default Ember returning false from the click handler of a submit button (`<button type="submit">`)  would *prevent* the `submit` event on the `<form>`, while in this addon it would not do so.

Still a bit unsure why that is. Related to #10, this is again the relevant jQuery event handling code: https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/event.js#L341-L344. You see they call `stopPropagation()` and `preventDefault()`. Should we do the same when getting a `false` from the event handler?

I can put another PR together when we agree on how exactly it should be...

CC @cibernox remembering you worked on dockyard's addons including probably their form stuff like oneway-controls or form-for, you did not encounter any related issues there?

**Comment by rwjblue** [comment]
> Should we do the same when getting a false from the event handler?

Yes. Updating [around here](https://github.com/rwjblue/ember-native-dom-event-dispatcher/blob/master/addon/index.js#L127) and [here](https://github.com/rwjblue/ember-native-dom-event-dispatcher/blob/master/addon/index.js#L109-L115) to be aware of `actionHandler` returning `false` would do the trick.
