### ISSUE TITLE
Exception thrown in Ember canary (3.1)

### ISSUE THREAD

**Issue by cibernox** [rwjblue/ember-native-dom-event-dispatcher#18]
The exception is that `this._bubbleEvent` is not a function:
https://github.com/rwjblue/ember-native-dom-event-dispatcher/blob/8c105061b8455e6f00015572cc5699b3e5045519/addon/index.js#L72

Steps to reproduce it:
1. Clone https://github.com/cibernox/ember-basic-dropdown
2. Update to canary: `"ember-source": "http://builds.emberjs.com/canary/daily/20180110.tgz",`
3. Boot the app without fastboot (which is also broken): `FASTBOOT_DISABLED=true ember serve`
4. Interact with the dropdown in the top of the page and see the error being logged many times.

**Comment by rwjblue** [comment]
Ember canary (and soon beta) removed support for `eventManager`, and did some additional cleanup resulting in`_bubbleEvent` not being a function any longer.

**Comment by rwjblue** [comment]
This was done in https://github.com/emberjs/ember.js/pull/16099

**Comment by rwjblue** [comment]
We need to make this addon a noop when using Ember 3.0+ (Ember internally supports native event handling when jQuery is not present)...

**Comment by cibernox** [comment]
I can take care. How would you do it? With ember-version-checked and a funnel to completely remove everything in the addon?

**Comment by rwjblue** [comment]
I think I would use `ember-cli-version-checker` to detect Ember version and do something like this:

```js
module.exports = {
  name: 'ember-native-dom-event-dispatcher',
  
  init() {
    this._super && this._super.init.apply(this, arguments);

    let checker = new VersionChecker(this);  
    this._shouldDisable = checker.forEmber().gt('3.0.0-beta.2');
  },

  treeFor(type) {
    if (this._shouldDisable) {
      return null;
    }

    return this._super.treeFor.apply(this, arguments);
  }
}
```
